name: aplikasi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.2.0
  dio: ^5.4.0
  dropdown_search: ^5.0.6
  supabase_flutter: ^2.4.0

  shared_preferences: ^2.3.2
  
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/logo/gold_logo.png
    - assets/logo/white_logo.png
    - assets/logo/black_logo.png
